secrets:
  m2settings:
    file: ~/.m2/settings.xml

services:
  gateway:
    build:
      context: ./gateway

  frontend:
    build:
      context: ./frontend
      args:
        APP_SHELL_VERSION: "9.0.2"
    volumes:
      - "./frontend-overrides/openmrs-config.json:/usr/share/nginx/html/openmrs-config.json:ro"
      - "./frontend-overrides/AfyaDME.png:/usr/share/nginx/html/AfyaDME.png:ro"
      - "./frontend-overrides/login-illustration.js:/usr/share/nginx/html/login-illustration.js:ro"
      - "./frontend-overrides/importmap.json:/usr/share/nginx/html/importmap.json:ro"
      - "./frontend-overrides/routes.registry.json:/usr/share/nginx/html/routes.registry.json:ro"
      - "./frontend-overrides/modules/openmrs-esm-service-queues-app-10.0.2:/usr/share/nginx/html/openmrs-esm-service-queues-app-10.0.2:ro"
      - "./frontend-overrides/modules/openmrs-esm-appointments-app-10.0.2:/usr/share/nginx/html/openmrs-esm-appointments-app-10.0.2:ro"
      - "./frontend-overrides/modules/path-drc-esm-orders-app-1.0.0:/usr/share/nginx/html/path-drc-esm-orders-app-1.0.0:ro"

  backend:
    build:
      secrets:
        - m2settings
      context: .
    volumes:
      - "../openmrs-content-path-drc/Base Content Package/configuration/backend_configuration/ordertypes:/openmrs/distribution/openmrs_config/ordertypes/path.drc:ro"
      - "../openmrs-content-path-drc/Base Content Package/configuration/backend_configuration/concepts:/openmrs/distribution/openmrs_config/concepts/path.drc:ro"
      - "./backend-modules/orderexpansion-1.0.1-SNAPSHOT.omod:/openmrs/distribution/openmrs_modules/orderexpansion-1.0.1-SNAPSHOT.omod:ro"
